### ISSUE TITLE
Overriding default jQuery UI styles and breaking the Node-RED Editor

### ISSUE THREAD

**Issue by knolleary** [bartbutenaers/node-red-contrib-ui-svg#56] opened 2020-04-15 12:33 UTC
This node is overriding some jQuery UI styles which is breaking the Node-RED editor.

Specifically this line: https://github.com/bartbutenaers/node-red-contrib-ui-svg/blob/53fedabbdee73c088e96ceb88fb76a88b30c1d47/svg_graphics.html#L21

This gets applied to *all* dialogs in the editor, not just those the ui-svg node uses. The result being the Import/Export dialogs in the editor no longer look right.

Please use class names that are specific to your nodes to ensure any CSS you define only applies to your elements.

This applies to both the jquery classes but your other classes. It would be good if they were all prefixes with something like `ui-svg-XYZ` to minimise the chance of a naming collision.

**Comment by Steve-Mcl** [comment] 2020-04-15 15:01
fixed in the panzoom branch (V2)

@bartbutenaers I'll leave it to you for merging / publshing. :)

**Closed** 2020-04-15 20:12 UTC

**Comment by bartbutenaers** [comment] 2020-04-15 21:11
Hi @knolleary,
Version 1.2.3 is now published on npm.
Hopefully the problem is solved now.
If not, please reopen this issue.
Bart
