### ISSUE TITLE
Not getting output from events since last update

### ISSUE THREAD

**Issue by smcgann99** [bartbutenaers/node-red-contrib-ui-svg#105] opened 2021-12-02 15:30 UTC
Bart,

Since last update none of my clickable icons are working. There is no output from svg node when they are clicked....

**Comment by bartbutenaers** [comment] 2021-12-02 17:43
@smcgann99,
Can you please provide a simple example flow?  I have executed lots of [tests](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/97#issuecomment-969374604) for similar issues recently, but I got ZERO response on that.  And on my [call](https://discourse.nodered.org/t/announce-node-red-contrib-ui-svg-v2-3-0-beta/52311?u=bartbutenaers) for beta testers, I got exactly the same amount of feedback...
Bart

**Comment by bartbutenaers** [comment] 2021-12-03 11:38
@smcgann99,
This is caused by this error:

![image](https://user-images.githubusercontent.com/14224149/144595021-8576a22c-bf2b-496d-bac2-eda3daf75717.png)

What happened:
1. In the last release (2.3.0) the hardcoded CSS has been replaced by customizable CSS (in the new tabsheet).
2. There was a bug in that code, so the Panzoom (and Hammer) scripts were loaded inside the CSS `style` tags.
3. Since that failed, the `$scope.init` failed.
4. As a result the next code was not being executed anymore, i.e. the event handlers were not applied anymore to your SVG shapes.

I have fixed this now on Github.  Could you please install the version from Github (from within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-ui-svg
```
Could you please do some extra tests, and let me know if there are any other things not working anymore in your dashboard?  

Thanks!!
Bart

**Comment by smcgann99** [comment] 2021-12-03 16:39
It looks like thats fixed it Bart. 

Many Thanks!

**Comment by bartbutenaers** [comment] 2021-12-04 07:57
Hi @smcgann99,
Thanks for the feedback!  Glad to hear that it is solved.
I will close this issue as soon as the new version is published on npm, to avoid that other users start posting duplicate issues...
Would like to solve the issue with the dashboard colors first, before I create a new version.
Bart

**Comment by bartbutenaers** [comment] 2021-12-08 21:11
The fix has been published as version ***2.3.1***

**Closed by bartbutenaers** 2021-12-08 21:11 UTC
Labels: bug
