### ISSUE TITLE
Too slow editing/saving node with huge SVG 

### ISSUE THREAD

**Issue by andreypopov** [bartbutenaers/node-red-contrib-ui-svg#50] opened 2020-03-05 06:57 UTC
my svg node is  100kb+
try to import, edit and save. We need some optimization here..
I use the latest macbook pro 2019/ 64gb ram

**Comment by andreypopov** [comment] 2020-03-05 06:58
[svg_huge.json.zip](https://github.com/bartbutenaers/node-red-contrib-ui-svg/files/4291398/svg_huge.json.zip)

**Comment by andreypopov** [comment] 2020-03-05 07:08
Just notice ver2.0 description, I have to try it

**Comment by bartbutenaers** [comment] 2020-03-05 21:52
Hi Andrey,
Damn yes that is slow.  At first sight I have no idea what could cause the problem...
Will need to investigate that, but I'm a bit overloaded at the moment.

The 2.0.0 version is not released yet on NPM due to the lack of time.
You need to install it directly from my Github account:
```
npm install bartbutenaers/node-red-contrib-ui-svg#panzoom
```

A question about your SVG:
```
<image width="1704px" height="695" id="background" xlink:href="/SVG.png" />
```
Could you explain where your png image is located, and how you expose it to the dashboard this way?  Was looking myself for a secure way to use private images inside my svg...

Bart

**Comment by bartbutenaers** [comment] 2020-03-05 22:39
P.S. The 2.0 version contains a breaking change unfortunately.  Please have a look at the start of the readme page for more information.

**Comment by andreypopov** [comment] 2020-03-11 07:10
Hi, I checked code and found super slow space. Speed improved from 10 seconds to 1 sec and there are no render lags.

 TypedInput is slow. You can try with these changes. (in 2 places)
![2020-03-11_10-01-22](https://user-images.githubusercontent.com/1624839/76390891-4fdb7400-637f-11ea-92aa-79362ecf60e6.png)

Do you have an idea how to change typedInput field and save payloadType functionality?

**Comment by andreypopov** [comment] 2020-03-11 07:49
The second slow place is - autocompletes. I suggest to add new option "disable autocompletes" for performance.

![2020-03-11_10-48-06](https://user-images.githubusercontent.com/1624839/76394051-e6129880-6385-11ea-8180-045ec10e1efe.png)

**Comment by bartbutenaers** [comment] 2020-03-11 15:20
Hi Andrey,
I REALLY appreciate the fact that you have analysed it by yourself!!!
This is a tremendous help...
But at the moment I'm recovering from a surgery, so will try to review your solution as soon as possible!
Will keep you updated,
Bart

**Comment by bartbutenaers** [comment] 2020-03-22 08:18
Morning @andreypopov,

Sorry for keep you waiting!
It is very helpful that you already spotted the two performance bottlenecks!!!

But before I merge your pull request, I would first like to try whether we can make it faster.  Just to be able to keep the same functionality for large SVG's.  If that fails I will have no other choice then using your checkboxes...

P.S. would you be so kind to respond to another issue [please](https://github.com/bartbutenaers/node-red-contrib-ui-svg/issues/35).  Perhaps you can explain there how you use your local image path.  Think you might help lot of users with that.  Thanks !!

## Autocomplete

Could you explain shortly how you have measured that the autocomplete was one of the bottlenecks?  I have added a _**fix**_ for the autocomplete on the "_panzoom_" branch.  Now the autocomplete is only added once the user clicks on an element, instead of adding autocomplete to all elements at conf screen startup:
```
targetIdField.click(function() { // Lazy load autocomplete for performance reasons
   targetIdField.autocomplete({
      source: function(req, add){
         add($.ui.autocomplete.filter(node.nonAnimationIds || [] , req.term));
      }
   });
});
```
I have done this for all autocomplete fields, so hopefully that helps.  Would be nice if you could install that branch and do your performance test, and let me know if I should keep this fix.

## TypedInput's

When I use the profiler of my Chrome developer tools, it seems there are an awful lot of resizing calculations for the TypedInput's:

![image](https://user-images.githubusercontent.com/14224149/77245174-e5e38a00-6c1c-11ea-807a-cabd331ee85b.png)

Which is being triggered as soon as we do an ```addItem``` of a typedInput:

![image](https://user-images.githubusercontent.com/14224149/77245187-027fc200-6c1d-11ea-8465-772fb0de9a0d.png)

I think it would be better if the resizing was executed once at the end...  But I have no clue at all whether that is possible.  Did you have the same conclusion, or did you see something else going wrong perhaps?  Seems this is a known [problem ](https://discourse.nodered.org/t/typedinput-performance-issue/22510), but they haven't solved the root cause since they have added workarounds to their nodes (change node...).  Don't think these workarounds could be introduced here, because they only apply now TypedInputs to visible fields.  But all our TypedInput fields are already visible in our table ...

I will discuss this on the forum as soon as I have time.  So please share me your analysis of the problem, so we can explain correctly to the folks what is going wrong...

Thanks !!!

Bart

**Comment by andreypopov** [comment] 2020-03-22 08:39
> Could you explain shortly how you have measured that the autocomplete was one of the bottlenecks? 
That was my suggestion, I disabled it and found performance boost. I don't know how to accurate measure it.
Your solution could help, I thought about it.

> Did you have the same conclusion, or did you see something else going wrong perhaps? 
Yes, the same conclusion. It is typedInput's issue. Can we init it onclick like autocompletes?  

btw. node's saving  is also so slooow..  my svg node is still growing :)

**Comment by bartbutenaers** [comment] 2020-03-30 21:04
Hey Andrey,

Sorry but I'm really short of free time lately.  I have now created a [discussion ](https://discourse.nodered.org/t/performance-issue-when-lots-of-typedinputs/23922)on the Node-RED forum, and hopefully I get the golden tip to solve this.

P.S. There is another workaround, since you can replace a series of event handlers by a single one, when you should use CSS selectors.  See an example on our [wiki ](https://github.com/bartbutenaers/node-red-contrib-ui-svg/wiki/Apply-an-event-to-multiple-shapes-(using-CSS-selectors))page.  Then your config page becomes more simple and readable.

Will keep you updated if I should get an answer from anybody.

Bart

**Comment by bartbutenaers** [comment] 2020-04-02 17:03
Good news,
Nick has responded on the Node-RED discussion.  He has redesigned the typedinput widget completely, to solve the performance issues.  It will be released in Node-RED version 1.0.5 in the near future

**Comment by bartbutenaers** [comment] 2020-04-09 19:56
Evening Andrey (@andreypopov),
Node-RED 1.0.5 has been published today.
I have installed it and now your SVG node config screen opens in **2 à 3 seconds**, which is very acceptable for me.  Especially since we don't have to disable the typedinputs, which would most probably result in other issues for other use cases afterwards.

But there is still a problem with the layouts of the typedinputs.  I have reported this [problem ](https://discourse.nodered.org/t/node-red-1-0-5-released/24522/3?u=bartbutenaers) and Nick has solved it already in Node-RED **1.0.6** (which will most probably released next week).

P.S. I did test this on the "_panzoom_" branch, which contains also my fix to lazy initialize the autocomplete fields.

**Comment by bartbutenaers** [comment] 2020-04-29 21:53
Hi @andreypopov,
I have tested it tonight with Node-RED **1.0.6.**
Your SVG node config screen still opens in 2 à 3 seconds, and the layouts of the typedinputs seem to be fixed correctly now.
Can you check whether the issue is solved for you with that Node-RED version?
Thanks!!

**Comment by bartbutenaers** [comment] 2020-05-16 05:34
Hi @andreypopov,
Would be nice if you could let me know if I can close this issue for the upcoming 2.0 release.
Thanks and have a nice weekend!

**Comment by bartbutenaers** [comment] 2020-06-25 22:56
I assume it is solved ...

**Closed by bartbutenaers** 2020-06-25 22:56 UTC
